# Site settings
title: Serene Chan
description: Digital Marketing Manager
email: serene_siyun3@hotmail.com
social_links:
  github: https://github.com/serenechansiyun
  linkedin: https://www.linkedin.com/in/serenechan/

url: "https://serenechansiyun.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

